### ISSUE TITLE
Using unit class as an instance

### ISSUE THREAD

**Issue by inutano** [bio-ontology-research-group/unit-ontology#7]
We would like to use unit ontology term to represent some values in RDF format. For example, a feature of a nucleotide sequence "GC content 50%". Currently I am doing with `uo:percent` like;

``` turtle
<a Nucleotide Sequence> myOntology:gcContent [
  sio:has_unit uo:percent;
  rdf:value 50;
] .
```

However, `uo:percent` is a class of unit, not an instance. Using blank node to create an instance of the class seems redundant. Is it possible to change definitions of those terms so that we can use them as instance, too?

**Comment by jimmccusker** [comment]
Simply using it as an instance like you did is sufficient to pun (in OWL 2) the UO term as an instance. There's no further work that needs to be done there, although you may want to add the type sio:UnitOfMeasure to them in a new graph, if you want to query for units.

Unrelated note: Note that in your case, you probably want to use sio:hasValue here instead of rdf:value.
