### ISSUE TITLE
Term request teaspoon, tablespoon

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/unit-ontology#8]
We are annotating foods and wonder if units such as "teaspoon", "tablespoon", or "cup" would be in the scope of UO.

**Comment by Public-Health-Bioinformatics** [comment]
I second that - volume measures; we'd like to include them in FoodOn.  "fluid ounce" as well. I see https://en.wikibooks.org/wiki/Cookbook:Units_of_measurement covers these.  Would you need SI equivalencies in the definitions?

**Comment by ddooley** [comment]
I have provided some technical labels and definitions for these terms since there is some variation in actual volume measurement based on country. We need them for FoodOn as we are soon capturing serving portion information for a USDA Agricultural Research Service ontology project.

I've added a language facet to help disambiguate the terms for text mining when text english dialect is known.  Hopefully UO can accommodate that? I'm open to shorter labels for US customary units if desired.

Your curation is much appreciated!

label: **"metric teaspoon"@en**
definition: a metric teaspoon is a unit of measurement of volume widely used in cooking recipes and pharmaceutic prescriptions. It equals a 5mL volume. 
synonym: "tsp"@en // abbreviation
synonym: "teaspoon"@en
definition source: https://en.wikipedia.org/wiki/Teaspoon

label: **"United States customary units teaspoon"@en-US**
definition: a United States customary units teaspoon is a unit of measurement of volume widely used in cooking recipes and pharmaceutic prescriptions in America. It equals a 4.93 mL volume. 
synonym: "tsp"@en-US // abbreviation
synonym: "teaspoon"@en-US
definition source: https://en.wikipedia.org/wiki/United_States_customary_units#Cooking_measures

label: **"metric tablespoon"@en**
definition: a metric tablespoon is a unit of measurement of volume widely used in cooking recipes and pharmaceutic prescriptions. It equals a 15mL volume. 
see Also: "Australian metric tablespoon".
synonym: "Tbsp"@en  // abbreviation ; note capitalization is standard
synonym: "tablespoon"@en
definition source: https://en.wikipedia.org/wiki/Tablespoon

label: **"Australian metric tablespoon"@en-AU**
definition: an Australian metric tablespoon is a unit of measurement of volume used in Australia for cooking recipes and pharmaceutic prescriptions. It equals a 20mL volume. 
synonym: "Tbsp"@en-AU  // abbreviation; note capitalization is standard
synonym: "tablespoon"@en-AU
definition source: https://en.wikipedia.org/wiki/Tablespoon

label: **"United States customary units tablespoon"@en-US**
definition: a United States customary units tablespoon is a unit of measurement of volume widely used in cooking recipes and pharmaceutic prescriptions in America. It equals a 14.79 mL volume. 
synonym: "Tbsp"@en-US // abbreviation
synonym: "tablespoon"@en-US
definition source: https://en.wikipedia.org/wiki/United_States_customary_units#Cooking_measures

label: **"metric cup"@en** 
definition: a metric cup is a unit of measurement of volume widely used in cooking recipes and pharmaceutic prescriptions. It equals a 250mL volume. 
synonym: "C"@en  // abbreviation; note capitalization is standard
definition source: https://en.wikipedia.org/wiki/Cooking_weights_and_measures

label: **"United States customary units cup"@en-US**
definition: a United States customary units cup is a unit of measurement of volume widely used in cooking recipes and pharmaceutic prescriptions in America. It equals a 236.59 mL volume. 
synonym: "C"@en-US // abbreviation; note capitalization is standard
definition source: https://en.wikipedia.org/wiki/United_States_customary_units#Cooking_measures

label: **"United States FDA cup"@en-US**
definition: a United States FDA cup is a unit of measurement of volume used by the US Federal Department of Agriculture as a nutritional serving measure. It equals a 240 mL volume. 
definition source: https://en.wikipedia.org/wiki/United_States_customary_units#Cooking_measures

**Comment by leechuck** [comment]
@reality Are you maintaining UO?

**Comment by ddooley** [comment]
Indeed - is the ontology under active curation?

**Comment by reality** [comment]
Hello. Yes, I am maintaining the ontology. I will add these terms tomorrow.

**Comment by reality** [comment]
Terms added in https://github.com/bio-ontology-research-group/unit-ontology/commit/2c773f6270c394195d18810322aeb3ed85aab5fe with IDs UO:0010040-UO:0010047

For now, I have not added EN dialect labels for customary units, since this is not implemented elsewhere in UO (no strings have language tags). However, this will be implemented soon per issue #19. For now, the metric units are the only classes to carry the simple "teaspoon" "tablespoon" etc labels.

**Comment by ddooley** [comment]
Great, much appreciated!
